spring:
  profiles:
    active: dev 
---
spring:
  profiles: dev
  messages:
    basename: i18n/Message
server: 
  port: 80
---
spring:
  profiles: beta
  messages:
    basename: i18n/Message
server: 
  port: 8082
---
spring:
  profiles: product
  messages:
    basename: i18n/Message
server: 
  port: 8083