spring:
  profiles:
    active: dev 
---
spring:
  profiles: dev
  messages:
    basename: i18n/Message
  thymeleaf:
    servlet:
      content-type: text/html 
    cache: false 
    mode: LEGACYHTML5

server: 
  port: 80
---
spring:
  profiles: beta
  messages:
    basename: i18n/Message
server: 
  port: 8082
---
spring:
  profiles: product
  messages:
    basename: i18n/Message
server: 
  port: 8083